export const CONDITION_TYPES = [
  { name: "None", min_max: false, min: null, max: null, values: [] },
  {
    name: "Random",
    min_max: false,
    min: "r",
    max: "r",
    values: ["r"],
    strings: ["Random"],
  },
  {
    name: "Characters",
    min_max: true,
    min: 1,
    max: 14,
    values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
    strings: [
      "Recruit 1 Characters",
      "Recruit 2 Characters",
      "Recruit 3 Characters",
      "Recruit 4 Characters",
      "Recruit 5 Characters",
      "Recruit 6 Characters",
      "Recruit 7 Characters",
      "Recruit 8 Characters",
      "Recruit 9 Characters",
      "Recruit 10 Characters",
      "Recruit 11 Characters",
      "Recruit 12 Characters",
      "Recruit 13 Characters",
      "Recruit 14 Characters",
    ],
  },
  {
    name: "Character",
    min_max: false,
    min: "r",
    max: 13,
    values: ["r", 6, 2, 4, 11, 12, 1, 10, 8, 5, 9, 3, 7, 0, 13],
    strings: [
      "Random",
      "Recruit Celes",
      "Recruit Cyan",
      "Recruit Edgar",
      "Recruit Gau",
      "Recruit Gogo",
      "Recruit Locke",
      "Recruit Mog",
      "Recruit Relm",
      "Recruit Sabin",
      "Recruit Setzer",
      "Recruit Shadow",
      "Recruit Strago",
      "Recruit Terra",
      "Recruit Umaro",
    ],
  },
  {
    name: "Espers",
    min_max: true,
    min: 1,
    max: 27,
    values: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 26, 27,
    ],
    strings: [
      "Find 1 Espers",
      "Find 2 Espers",
      "Find 3 Espers",
      "Find 4 Espers",
      "Find 5 Espers",
      "Find 6 Espers",
      "Find 7 Espers",
      "Find 8 Espers",
      "Find 9 Espers",
      "Find 10 Espers",
      "Find 11 Espers",
      "Find 12 Espers",
      "Find 13 Espers",
      "Find 14 Espers",
      "Find 15 Espers",
      "Find 16 Espers",
      "Find 17 Espers",
      "Find 18 Espers",
      "Find 19 Espers",
      "Find 20 Espers",
      "Find 21 Espers",
      "Find 22 Espers",
      "Find 23 Espers",
      "Find 24 Espers",
      "Find 25 Espers",
      "Find 26 Espers",
      "Find 27 Espers",
    ],
  },
  {
    name: "Esper",
    min_max: false,
    min: "r",
    max: 18,
    values: [
      "r",
      14,
      13,
      7,
      19,
      15,
      24,
      22,
      1,
      17,
      6,
      11,
      9,
      20,
      26,
      16,
      12,
      0,
      2,
      5,
      3,
      21,
      25,
      8,
      4,
      10,
      23,
      18,
    ],
    strings: [
      "Random",
      "Find Alexandr",
      "Find Bahamut",
      "Find Bismark",
      "Find Carbunkl",
      "Find Crusader",
      "Find Fenrir",
      "Find Golem",
      "Find Ifrit",
      "Find Kirin",
      "Find Maduin",
      "Find Odin",
      "Find Palidor",
      "Find Phantom",
      "Find Phoenix",
      "Find Ragnarok",
      "Find Raiden",
      "Find Ramuh",
      "Find Shiva",
      "Find Shoat",
      "Find Siren",
      "Find Sraphim",
      "Find Starlet",
      "Find Stray",
      "Find Terrato",
      "Find Tritoch",
      "Find Unicorn",
      "Find ZoneSeek",
    ],
  },
  {
    name: "Dragons",
    min_max: true,
    min: 1,
    max: 8,
    values: [1, 2, 3, 4, 5, 6, 7, 8],
    strings: [
      "Defeat 1 Dragons",
      "Defeat 2 Dragons",
      "Defeat 3 Dragons",
      "Defeat 4 Dragons",
      "Defeat 5 Dragons",
      "Defeat 6 Dragons",
      "Defeat 7 Dragons",
      "Defeat 8 Dragons",
    ],
  },
  {
    name: "Dragon",
    min_max: false,
    min: "r",
    max: 7,
    values: ["r", 0, 1, 2, 3, 4, 5, 6, 7],
    strings: [
      "Random",
      "Defeat Blue Drgn",
      "Defeat Dirt Drgn",
      "Defeat Gold Drgn",
      "Defeat Ice Dragon",
      "Defeat Red Dragon",
      "Defeat Skull Drgn",
      "Defeat Storm Drgn",
      "Defeat White Drgn",
    ],
  },
  {
    name: "Bosses",
    min_max: true,
    min: 1,
    max: 39,
    values: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
    ],
    strings: [
      "Defeat 1 Bosses",
      "Defeat 2 Bosses",
      "Defeat 3 Bosses",
      "Defeat 4 Bosses",
      "Defeat 5 Bosses",
      "Defeat 6 Bosses",
      "Defeat 7 Bosses",
      "Defeat 8 Bosses",
      "Defeat 9 Bosses",
      "Defeat 10 Bosses",
      "Defeat 11 Bosses",
      "Defeat 12 Bosses",
      "Defeat 13 Bosses",
      "Defeat 14 Bosses",
      "Defeat 15 Bosses",
      "Defeat 16 Bosses",
      "Defeat 17 Bosses",
      "Defeat 18 Bosses",
      "Defeat 19 Bosses",
      "Defeat 20 Bosses",
      "Defeat 21 Bosses",
      "Defeat 22 Bosses",
      "Defeat 23 Bosses",
      "Defeat 24 Bosses",
      "Defeat 25 Bosses",
      "Defeat 26 Bosses",
      "Defeat 27 Bosses",
      "Defeat 28 Bosses",
      "Defeat 29 Bosses",
      "Defeat 30 Bosses",
      "Defeat 31 Bosses",
      "Defeat 32 Bosses",
      "Defeat 33 Bosses",
      "Defeat 34 Bosses",
      "Defeat 35 Bosses",
      "Defeat 36 Bosses",
      "Defeat 37 Bosses",
      "Defeat 38 Bosses",
      "Defeat 39 Bosses",
    ],
  },
  {
    name: "Boss",
    min_max: false,
    min: "r",
    max: 38,
    values: [
      "r",
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
    ],
    strings: [
      "Random",
      "Defeat Air Force",
      "Defeat Atma",
      "Defeat AtmaWeapon",
      "Defeat Chadarnook",
      "Defeat Cranes",
      "Defeat Dadaluma",
      "Defeat Doom",
      "Defeat Doom Gaze",
      "Defeat Dullahan",
      "Defeat FlameEater",
      "Defeat GhostTrain",
      "Defeat Goddess",
      "Defeat Guardian",
      "Defeat Hidon",
      "Defeat Ifrit/Shiva",
      "Defeat Inferno",
      "Defeat Kefka (Narshe)",
      "Defeat Leader",
      "Defeat MagiMaster",
      "Defeat Nerapa",
      "Defeat Number 024",
      "Defeat Number 128",
      "Defeat Phunbaba 3",
      "Defeat Phunbaba 4",
      "Defeat Poltrgeist",
      "Defeat Rizopas",
      "Defeat SrBehemoth",
      "Defeat Stooges",
      "Defeat Tentacles",
      "Defeat Tritoch",
      "Defeat TunnelArmr",
      "Defeat Ultros 1",
      "Defeat Ultros 2",
      "Defeat Ultros 3",
      "Defeat Ultros/Chupon",
      "Defeat Umaro",
      "Defeat Vargas",
      "Defeat Whelk",
      "Defeat Wrexsoul",
    ],
  },
  {
    name: "Checks",
    min_max: true,
    min: 1,
    max: 59,
    values: [
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
      22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
      40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
      58, 59,
    ],
    strings: [
      "Complete 1 Checks",
      "Complete 2 Checks",
      "Complete 3 Checks",
      "Complete 4 Checks",
      "Complete 5 Checks",
      "Complete 6 Checks",
      "Complete 7 Checks",
      "Complete 8 Checks",
      "Complete 9 Checks",
      "Complete 10 Checks",
      "Complete 11 Checks",
      "Complete 12 Checks",
      "Complete 13 Checks",
      "Complete 14 Checks",
      "Complete 15 Checks",
      "Complete 16 Checks",
      "Complete 17 Checks",
      "Complete 18 Checks",
      "Complete 19 Checks",
      "Complete 20 Checks",
      "Complete 21 Checks",
      "Complete 22 Checks",
      "Complete 23 Checks",
      "Complete 24 Checks",
      "Complete 25 Checks",
      "Complete 26 Checks",
      "Complete 27 Checks",
      "Complete 28 Checks",
      "Complete 29 Checks",
      "Complete 30 Checks",
      "Complete 31 Checks",
      "Complete 32 Checks",
      "Complete 33 Checks",
      "Complete 34 Checks",
      "Complete 35 Checks",
      "Complete 36 Checks",
      "Complete 37 Checks",
      "Complete 38 Checks",
      "Complete 39 Checks",
      "Complete 40 Checks",
      "Complete 41 Checks",
      "Complete 42 Checks",
      "Complete 43 Checks",
      "Complete 44 Checks",
      "Complete 45 Checks",
      "Complete 46 Checks",
      "Complete 47 Checks",
      "Complete 48 Checks",
      "Complete 49 Checks",
      "Complete 50 Checks",
      "Complete 51 Checks",
      "Complete 52 Checks",
      "Complete 53 Checks",
      "Complete 54 Checks",
      "Complete 55 Checks",
      "Complete 56 Checks",
      "Complete 57 Checks",
      "Complete 58 Checks",
      "Complete 59 Checks",
    ],
  },
  {
    name: "Check",
    min_max: false,
    min: "r",
    max: 58,
    values: [
      "r",
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44,
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54,
      55,
      56,
      57,
      58,
    ],
    strings: [
      "Random",
      "Ancient Castle",
      "Ancient Castle Dragon",
      "Baren Falls",
      "Burning House",
      "Collapsing House",
      "Daryl's Tomb",
      "Doma Siege",
      "Doma Dream Door",
      "Doma Dream Awaken",
      "Doma Dream Throne",
      "Ebot's Rock",
      "Esper Mountain",
      "Fanatic's Tower Dragon",
      "Fanatic's Tower Leader",
      "Fanatic's Tower Follower",
      "Figaro Castle Throne",
      "Figaro Castle Engine",
      "Floating Cont. Arrive",
      "Floating Cont. Beast",
      "Floating Cont. Escape",
      "Gau's Father's House",
      "Imperial Camp",
      "Kefka's Tower Cell Beast",
      "Kefka's Tower Dragon G",
      "Kefka's Tower Dragon S",
      "Kohlingen Cafe",
      "Lete River",
      "Lone Wolf Chase",
      "Lone Wolf Moogle Room",
      "Magitek Factory Trash",
      "Magitek Factory Guard",
      "Magitek Factory Finish",
      "Mobliz Attack",
      "Mt. Kolts",
      "Mt. Zozo",
      "Mt. Zozo Dragon",
      "Narshe Battle",
      "Narshe Dragon",
      "Narshe Weapon Shop",
      "Narshe Weapon Shop Mines",
      "Opera House Disruption",
      "Opera House Dragon",
      "Owzer's Mansion",
      "Phantom Train",
      "Phoenix Cave",
      "Phoenix Cave Dragon",
      "Sealed Gate",
      "Search The Skies",
      "Serpent Trench",
      "South Figaro Prisoner",
      "South Figaro Cave",
      "Tritoch Cliff",
      "Tzen Thief",
      "Umaro's Cave",
      "Veldt",
      "Veldt Cave",
      "Whelk Gate",
      "Zone Eater",
      "Zozo Tower",
    ],
  },
  {
    name: "Quest",
    min_max: false,
    min: "r",
    max: 9,
    values: ["r", 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    strings: [
      "Random",
      "Defeat Sealed Cave Ninja",
      "Help Injured Lad",
      "Let Cid Die",
      "Pass Security Checkpoint",
      "Perform In Opera",
      "Save Cid",
      "Set Zozo Clock",
      "Suplex A Train",
      "Win An Auction",
      "Win A Coliseum Match",
    ],
  },
];
