import Head from 'next/head';
import type { NextPage } from 'next';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import newStyles from './index.module.css';
import { cva } from 'cva';
const S = {
  main: cva([newStyles.main]),
  backgroundImage: cva([newStyles.bgImage]),
  container: cva([newStyles.container]),
  description: cva([newStyles.description]),
  imageContainer: cva([newStyles.imageContainer])
};
const Home: NextPage = () => {
  return (
    <>
      <div className={S.backgroundImage()}></div>
      <div className={S.container()}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={S.main()}>
          <p className={S.imageContainer()}>
            <img src="/thumbnaillogoblack.png" alt="bg" />
          </p>

          <p className={S.description()}>
            Final Fantasy VI Worlds Collide is an open-world romhack and scavenger hunt randomizer for Final
            Fantasy VI for the SNES (originally released in English as Final Fantasy III).
          </p>

          <div className={styles.grid}>
            <a href="https://wiki.ff6wc.com/" className={styles.card} target="_blank" rel="noreferrer">
              <h2>Wiki &rarr;</h2>
              <p>Find in-depth information about WorldsCollide</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in </p>
            </a>

            <a href="https://linktr.ee/ff6wc" className={styles.card} target="_blank" rel="noreferrer">
              <h2>Social Media &rarr;</h2>
              <p>Follow us on social media to get the latest news, updates etc.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
            </a>
          </div>
        </main>

        {/* <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer> */}
      </div>
    </>
  );
};

export default Home;
